/**
 * THIS FILE IS AUTOMATICALLY GENERATED BY genColors.js.
 *
 * DO NOT MANUALLY MODIFY THIS FILE.
 */

enum ColorVariableLightModeName {
  BackgroundOverlay = "--color-backgroundOverlay-lightMode",
  BeigeDark = "--color-beigeDark-lightMode",
  BeigeLight = "--color-beigeLight-lightMode",
  Dimmer = "--color-dimmer-lightMode",
  Ghost = "--color-ghost-lightMode",
  Navy = "--color-navy-lightMode",
  NavyHover = "--color-navyHover-lightMode",
  Pink = "--color-pink-lightMode",
  Rust = "--color-rust-lightMode",
  WinterGreen = "--color-winterGreen-lightMode",
  Yellow = "--color-yellow-lightMode",
}

export default ColorVariableLightModeName;
