/**
 * THIS FILE IS AUTOMATICALLY GENERATED BY genColors.js.
 *
 * DO NOT MANUALLY MODIFY THIS FILE.
 */

enum ColorVariableDarkModeName {
  BackgroundOverlay = "--color-backgroundOverlay-darkMode",
  BeigeDark = "--color-beigeDark-darkMode",
  BeigeLight = "--color-beigeLight-darkMode",
  Dimmer = "--color-dimmer-darkMode",
  Ghost = "--color-ghost-darkMode",
  Navy = "--color-navy-darkMode",
  NavyHover = "--color-navyHover-darkMode",
  Pink = "--color-pink-darkMode",
  Rust = "--color-rust-darkMode",
  WinterGreen = "--color-winterGreen-darkMode",
  Yellow = "--color-yellow-darkMode",
}

export default ColorVariableDarkModeName;
